/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package invertorymanagementsystem;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;

/**
 *
 * @author ibnay
 */
public class employeeSelfInfo extends javax.swing.JFrame {

    /**
     * Creates new form employeeSelfInfo
     */
    private String E_ID;
    private ResultSet Data;
    
    public employeeSelfInfo(ResultSet data) throws SQLException {
        this.Data = data;
        E_ID = data.getString("Employee_ID");
        initComponents();
        EmployeeId.setText(data.getString("Employee_ID"));
        F_name.setText(data.getString("Employee_First_Name"));
        L_name.setText(data.getString("Employee_Last_Name"));
        U_name.setText(data.getString("Employee_User_Name"));
        PhoneNo.setText(data.getString("phone"));
        Email.setText(data.getString("Email"));
        password.setText(data.getString("Employee_Pasword"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        EmployeeId = new javax.swing.JLabel();
        EmployeeId1 = new javax.swing.JLabel();
        EmployeeId2 = new javax.swing.JLabel();
        EmployeeId3 = new javax.swing.JLabel();
        EmployeeId4 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        L_name = new javax.swing.JTextField();
        F_name = new javax.swing.JTextField();
        U_name = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        PhoneNo = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        iconLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(233, 166, 100));
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        EmployeeId.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        EmployeeId.setForeground(new java.awt.Color(233, 166, 100));
        EmployeeId.setText("ID");

        EmployeeId1.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        EmployeeId1.setForeground(new java.awt.Color(233, 166, 100));
        EmployeeId1.setText("First Name");

        EmployeeId2.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        EmployeeId2.setForeground(new java.awt.Color(233, 166, 100));
        EmployeeId2.setText("Last Name");

        EmployeeId3.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        EmployeeId3.setForeground(new java.awt.Color(233, 166, 100));
        EmployeeId3.setText("User Name");

        EmployeeId4.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        EmployeeId4.setForeground(new java.awt.Color(233, 166, 100));
        EmployeeId4.setText("Password");

        password.setBackground(new java.awt.Color(51, 51, 51));
        password.setForeground(new java.awt.Color(233, 166, 100));
        password.setText("jPasswordField1");
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        L_name.setBackground(new java.awt.Color(51, 51, 51));
        L_name.setForeground(new java.awt.Color(233, 166, 100));
        L_name.setText("jTextField1");
        L_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L_nameActionPerformed(evt);
            }
        });

        F_name.setBackground(new java.awt.Color(51, 51, 51));
        F_name.setForeground(new java.awt.Color(233, 166, 100));
        F_name.setText("jTextField1");
        F_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F_nameActionPerformed(evt);
            }
        });

        U_name.setBackground(new java.awt.Color(51, 51, 51));
        U_name.setForeground(new java.awt.Color(233, 166, 100));
        U_name.setText("jTextField1");
        U_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                U_nameActionPerformed(evt);
            }
        });

        saveButton.setBackground(new java.awt.Color(51, 51, 51));
        saveButton.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        saveButton.setForeground(new java.awt.Color(233, 166, 100));
        saveButton.setText("SAVE");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        PhoneNo.setBackground(new java.awt.Color(51, 51, 51));
        PhoneNo.setForeground(new java.awt.Color(233, 166, 100));
        PhoneNo.setText("Phone No");
        PhoneNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneNoActionPerformed(evt);
            }
        });

        Email.setBackground(new java.awt.Color(51, 51, 51));
        Email.setForeground(new java.awt.Color(233, 166, 100));
        Email.setText("Email");
        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });

        iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scaled"+"Eee1001"+".png")));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(EmployeeId3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EmployeeId2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EmployeeId1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EmployeeId4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(EmployeeId, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(U_name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(L_name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                .addComponent(F_name, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Email, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 56, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(saveButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmployeeId, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(iconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmployeeId1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F_name))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EmployeeId2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_name))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmployeeId3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(U_name))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmployeeId4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(saveButton)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.dispose();
        try {
            new homeScreen(Data).setVisible(true);
        } catch (SQLException ex) {
        }
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void L_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_L_nameActionPerformed

    private void F_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_F_nameActionPerformed

    private void U_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_U_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_U_nameActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            // TODO add your handling code here:
            DBO db = new DBO ("Employee");
            Connection conn = db.getConnection();
            CallableStatement stat = conn.prepareCall("{call update_Employee(?,?,?,?,?,?,?)}");
            stat.setString(1, EmployeeId.getText());
            stat.setString(2, F_name.getText());
            stat.setString(3, L_name.getText());
            stat.setString(4, U_name.getText());
            stat.setInt(5, Integer.parseInt(password.getText()));
            stat.setString(6, PhoneNo.getText());
            stat.setString(7, Email.getText());
            stat.execute();
            UIManager UI = new UIManager();
            UI.put("OptionPane.background", new ColorUIResource(51,51,51));
            UI.put("Panel.background", new ColorUIResource(51,51,51));
            
            if(!(EmployeeId.getText().equals(Data.getString("Employee_ID")) && F_name.getText().equals(Data.getString("Employee_First_Name")) 
                    && L_name.getText().equals(Data.getString("Employee_Last_Name")) && U_name.getText().equals(Data.getString("Employee_User_Name")) 
                    && password.getText().equals(Data.getString("Employee_Pasword")) && PhoneNo.getText().equals(Data.getString("phone")) 
                    && Email.getText().equals(Data.getString("Email")))){
                if(password.getText().equals(Data.getString("Employee_Pasword"))){
                    JOptionPane.showMessageDialog(null," ","Changes made",0);
                    this.dispose();
                    db = new DBO("Employee");
                    ResultSet data = db.getResult();
                    while(data.next()){
                        if(U_name.getText().equals(data.getString("Employee_User_name")) && password.getText().equals(data.getString("Employee_pasword"))){
                         new homeScreen(data).setVisible(true);
                            this.dispose();
                            break;
                            }
                    }
                }else{
                    JOptionPane.showMessageDialog(null,"You are getting logged out\nYour new Password is \""+password.getText()+"\".","Changes made",0);
                    this.dispose();
                    new Login(false).setVisible(true);
                }
                       
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(employeeSelfInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void PhoneNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneNoActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Email;
    private javax.swing.JLabel EmployeeId;
    private javax.swing.JLabel EmployeeId1;
    private javax.swing.JLabel EmployeeId2;
    private javax.swing.JLabel EmployeeId3;
    private javax.swing.JLabel EmployeeId4;
    private javax.swing.JTextField F_name;
    private javax.swing.JTextField L_name;
    private javax.swing.JTextField PhoneNo;
    private javax.swing.JTextField U_name;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
