/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package invertorymanagementsystem;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;

/**
 *
 * @author ibnay
 */
public class homeScreen extends javax.swing.JFrame {

    private String E_ID;
    private ResultSet Data;

    /**
     * Creates new form homeScreen
     */
    public homeScreen(ResultSet data) throws SQLException {
        Data = data;
        this.E_ID = data.getString("Employee_ID");
        initComponents();
        HiUser.setText("Hi " + data.getString("Employee_First_name") +" "+data.getString("Employee_Last_name") + "!");
        E_ID_label.setText(data.getString("Employee_ID"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        EmployeePic = new javax.swing.JLabel();
        HiUser = new javax.swing.JLabel();
        E_ID_label = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        EmployeePic1 = new javax.swing.JLabel();
        EmployeePic2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        EmployeePic4 = new javax.swing.JLabel();
        Inventory = new javax.swing.JLabel();
        EmployeePic5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(233, 166, 100));

        jLabel2.setFont(new java.awt.Font("Dubai", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(233, 166, 100));
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setForeground(new java.awt.Color(233, 166, 100));

        EmployeePic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/"+"Eee1001"+".png")));
        EmployeePic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmployeePicMouseClicked(evt);
            }
        });

        HiUser.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        HiUser.setForeground(new java.awt.Color(233, 166, 100));
        HiUser.setText("Hi USER!");

        E_ID_label.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        E_ID_label.setForeground(new java.awt.Color(233, 166, 100));
        E_ID_label.setText("E_ID");

        logoutButton.setBackground(new java.awt.Color(51, 51, 51));
        logoutButton.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(233, 166, 100));
        logoutButton.setText("LOG0UT");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EmployeePic, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HiUser, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(E_ID_label, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logoutButton))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(HiUser, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(E_ID_label, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(logoutButton))
                    .addComponent(EmployeePic, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Felix Titling", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(233, 166, 100));
        jLabel4.setText("INSPIRATION");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(233, 166, 100));
        jLabel1.setText("PRODUCT");

        EmployeePic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/productIcon.png"))); // NOI18N
        EmployeePic1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmployeePic1MouseClicked(evt);
            }
        });

        EmployeePic2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/categoryIcon.png"))); // NOI18N
        EmployeePic2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmployeePic2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(233, 166, 100));
        jLabel3.setText("DEPARTMENT");

        EmployeePic4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/orderIcon.png"))); // NOI18N
        EmployeePic4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmployeePic4MouseClicked(evt);
            }
        });

        Inventory.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Inventory.setForeground(new java.awt.Color(233, 166, 100));
        Inventory.setText("Inventory");

        EmployeePic5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userMenuIcon.png"))); // NOI18N
        EmployeePic5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EmployeePic5MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(233, 166, 100));
        jLabel7.setText("USER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(EmployeePic5)
                        .addContainerGap(132, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(154, 154, 154))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(330, 330, 330))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(EmployeePic1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmployeePic4)
                    .addComponent(Inventory))
                .addGap(177, 177, 177)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmployeePic2)
                    .addComponent(jLabel3))
                .addGap(88, 88, 88))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmployeePic5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Inventory)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmployeePic1)
                            .addComponent(EmployeePic4))
                        .addGap(98, 98, 98)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(EmployeePic2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void EmployeePicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeePicMouseClicked
        try {
            // TODO add your handling code here:
            this.dispose();
            new employeeSelfInfo(Data).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(homeScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EmployeePicMouseClicked

    private void EmployeePic1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeePic1MouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            this.dispose();
            new productMenu(Data.getString("Employee_ID")).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(homeScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EmployeePic1MouseClicked

    private void EmployeePic2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeePic2MouseClicked
        try {
            // TODO add your handling code here:
            this.dispose();
            new departmentMenu(Data).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(homeScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EmployeePic2MouseClicked

    private void EmployeePic4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeePic4MouseClicked
        try {
            // TODO add your handling code here:
            this.dispose();
            new inventoryMenu(E_ID).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(homeScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EmployeePic4MouseClicked

    private void EmployeePic5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeePic5MouseClicked
        try {
            // TODO add your handling code here:
            if(E_ID.charAt(3)=='1'){
                this.dispose();
                new UserMenu(E_ID).setVisible(true);
                }
            else{
                UIManager UI = new UIManager();
                UI.put("OptionPane.background", new ColorUIResource(51,51,51));
                UI.put("Panel.background", new ColorUIResource(233,166,100));
                JOptionPane.showMessageDialog(null,"Sorry Asshole!","ERROR",0);
            }
        } catch (SQLException ex) {
            Logger.getLogger(homeScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_EmployeePic5MouseClicked

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Login(false).setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel E_ID_label;
    private javax.swing.JLabel EmployeePic;
    private javax.swing.JLabel EmployeePic1;
    private javax.swing.JLabel EmployeePic2;
    private javax.swing.JLabel EmployeePic4;
    private javax.swing.JLabel EmployeePic5;
    private javax.swing.JLabel HiUser;
    private javax.swing.JLabel Inventory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logoutButton;
    // End of variables declaration//GEN-END:variables
}
