/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package invertorymanagementsystem;

/**
 *
 * @author ibnay
 */
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.event.KeyEvent;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.ColorUIResource;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Grace
 */
public class POS extends javax.swing.JFrame {
    int quant;
    float Totel;
    float pPrice;
    float btotel=0;
    String pid;
    String pName;
    ConnectionHelper db;
    boolean keyp=false;
    DefaultTableModel model;
    int custID=0;
    int orderID = 0;
    String EmpId;
    String Name;
    String Counter="C2";
    
    ConnectionHelper helper;
   Connection conn;
   PreparedStatement pst;
   ResultSet rs;
    public POS(String EmpId,String Name) {
        initComponents();
        this.EmpId=EmpId;
        this.Name=Name;
        abc();
        EmployeeId.setText(EmpId);
        Ename.setText(Name);
        CustId1.setText(String.valueOf(custID));
      
    }
    void abc(){
        
          try {
            helper =new ConnectionHelper ("customer");
            conn = helper.getConnection();
             pst = conn.prepareStatement("select Customer_ID from customer order by Customer_ID desc ");
            rs = pst.executeQuery();
            
            if(rs.next())
                custID = custID + rs.getInt("Customer_ID") ;
            
            custID++;
            
            
             pst = conn.prepareStatement("select Bill_ID from bill_products order by Bill_ID desc");
            rs = pst.executeQuery();
            
            if(rs.next()){
                orderID = orderID + rs.getInt("Bill_ID") ;
            }
            orderID++;
            
            
             pst = conn.prepareStatement("INSERT INTO customer VALUES (?,?)");
             pst.setInt(1, custID);
             pst.setInt(2, orderID);
            pst.executeUpdate();
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(POS.class.getName()).log(Level.SEVERE, null, ex);
        } catch(Exception ex){
            
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        productId = new javax.swing.JTextField();
        addButton1 = new javax.swing.JButton();
        Qunatity = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        EmployeeId = new javax.swing.JTextField();
        Ename = new javax.swing.JTextField();
        clearButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Grand_total = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Pay = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        deleteButton2 = new javax.swing.JButton();
        editButton3 = new javax.swing.JButton();
        printButton4 = new javax.swing.JButton();
        Balance = new javax.swing.JTextField();
        CustId1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1333, 720));
        setPreferredSize(new java.awt.Dimension(1333, 720));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(233, 166, 100));
        jLabel1.setText("Quantity");

        productId.setBackground(new java.awt.Color(233, 166, 100));
        productId.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        productId.setToolTipText("");
        productId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productIdActionPerformed(evt);
            }
        });
        productId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                productIdKeyPressed(evt);
            }
        });

        addButton1.setBackground(new java.awt.Color(51, 51, 51));
        addButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        addButton1.setForeground(new java.awt.Color(233, 166, 100));
        addButton1.setText("Add");
        addButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButton1ActionPerformed(evt);
            }
        });

        Qunatity.setValue(1);
        quant=Integer.parseInt(Qunatity.getValue().toString());
        Qunatity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                QunatityStateChanged(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(233, 166, 100));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(233, 166, 100));
        jLabel2.setText("Product ID");

        jLabel7.setBackground(new java.awt.Color(233, 166, 100));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(233, 166, 100));
        jLabel7.setText("Employee Name");

        jLabel8.setBackground(new java.awt.Color(233, 166, 100));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(233, 166, 100));
        jLabel8.setText("Employee ID");

        EmployeeId.setBackground(new java.awt.Color(233, 166, 100));
        EmployeeId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeIdActionPerformed(evt);
            }
        });

        Ename.setBackground(new java.awt.Color(233, 166, 100));
        Ename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnameActionPerformed(evt);
            }
        });

        clearButton5.setBackground(new java.awt.Color(51, 51, 51));
        clearButton5.setForeground(new java.awt.Color(233, 166, 100));
        clearButton5.setText("Clear");
        clearButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel7)
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EmployeeId, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(Ename))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(productId, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Qunatity, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(clearButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabel8)
                    .addContainerGap(995, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmployeeId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Qunatity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(productId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(3, 3, 3)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(31, 31, 31))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Ename, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jLabel8)
                    .addContainerGap(78, Short.MAX_VALUE)))
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(233, 166, 100));
        jLabel3.setText("Customer_ID");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(233, 166, 100));
        jLabel4.setText("Total");

        Grand_total.setBackground(new java.awt.Color(233, 166, 100));
        Grand_total.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(233, 166, 100));
        jLabel5.setText("Balance");

        Pay.setBackground(new java.awt.Color(233, 166, 100));
        Pay.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(233, 166, 100));
        jLabel6.setText("Pay");

        deleteButton2.setBackground(new java.awt.Color(51, 51, 51));
        deleteButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        deleteButton2.setForeground(new java.awt.Color(233, 166, 100));
        deleteButton2.setText("Delete");
        deleteButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButton2ActionPerformed(evt);
            }
        });

        editButton3.setBackground(new java.awt.Color(51, 51, 51));
        editButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        editButton3.setForeground(new java.awt.Color(233, 166, 100));
        editButton3.setText("Edit");
        editButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButton3ActionPerformed(evt);
            }
        });

        printButton4.setBackground(new java.awt.Color(51, 51, 51));
        printButton4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        printButton4.setForeground(new java.awt.Color(233, 166, 100));
        printButton4.setText("Print Bill");
        printButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButton4ActionPerformed(evt);
            }
        });

        Balance.setBackground(new java.awt.Color(233, 166, 100));
        Balance.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        CustId1.setBackground(new java.awt.Color(233, 166, 100));
        CustId1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(printButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(deleteButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel4)))
                .addGap(0, 27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(66, 66, 66))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(113, 113, 113))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(87, 87, 87))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Grand_total)
                                    .addComponent(Pay)
                                    .addComponent(Balance, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                                .addGap(71, 71, 71))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(CustId1)
                        .addGap(19, 19, 19))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CustId1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Grand_total, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pay, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Balance, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deleteButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(editButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(printButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        productTable.setBackground(new java.awt.Color(233, 166, 100));
        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Product price", "Quantity", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(productTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productIdActionPerformed

    private void addButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButton1ActionPerformed
        
        if (keyp==false){
            pid=productId.getText();
            
            
            boolean found=false;
            
            try { 
                
            db = new ConnectionHelper("products");
            ResultSet data = db.getResult();
            
            while(data.next()){
                
                if(pid.equals(data.getString("Product_ID"))){
                    found=true;
                    pName=data.getString("Product_Name");
                    pPrice=Float.parseFloat(data.getString("Price"));
                    Totel=pPrice*quant;
            btotel=btotel+Totel;
            Grand_total.setText(String.valueOf(btotel));
            model=new DefaultTableModel();
            model=(DefaultTableModel)productTable.getModel();
            model.addRow(new Object[]{
            pid,
            pName,
            pPrice,
            quant,
            Totel,
        
            
            
            
    });
                }
            }
                System.out.println("5");
            if(found==false){
                UIManager UI = new UIManager();
                System.out.println("6");
                UI.put("OptionPane.background", new ColorUIResource(51,51,51));
                UI.put("Panel.background", new ColorUIResource(51,51,51));
                JOptionPane.showMessageDialog(null,"Product ID not found","ERROR",0);
            }
        } catch (SQLException ex) {
        }
        }
        
            
        productId.setText("");
        Qunatity.setValue(1);
        
        
                
    }//GEN-LAST:event_addButton1ActionPerformed

    private void deleteButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButton2ActionPerformed
        int rowno=productTable.getSelectedRow();
        Float am=Float.parseFloat(model.getValueAt(rowno, 4).toString());
        model.removeRow(rowno);
        Grand_total.setText(String.valueOf(Float.parseFloat(Grand_total.getText())-am));
    }//GEN-LAST:event_deleteButton2ActionPerformed

    private void PayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PayActionPerformed

    private void EmployeeIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeeIdActionPerformed

    private void EnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EnameActionPerformed

    private void productIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_productIdKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            keyp=true;
            pid=productId.getText();
            
            
            boolean found=false;
            
            try { 
                
            db = new ConnectionHelper("products");
            ResultSet data = db.getResult();
            
            while(data.next()){
                
                if(pid.equals(data.getString("Product_ID"))){
                    found=true;
                    pName=data.getString("Product_Name");
                    pPrice=Float.parseFloat(data.getString("Price"));
                }
            }
                
            if(found==false){
                UIManager UI = new UIManager();
                
                UI.put("OptionPane.background", new ColorUIResource(51,51,51));
                UI.put("Panel.background", new ColorUIResource(51,51,51));
                JOptionPane.showMessageDialog(null,"Product ID not found","ERROR",0);
            }
        } catch (SQLException ex) {
        }
        }
    }//GEN-LAST:event_productIdKeyPressed

    private void clearButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButton5ActionPerformed
        // TODO add your handling code here:
        productId.setText("");
        Qunatity.setValue(1);
        
    }//GEN-LAST:event_clearButton5ActionPerformed

    private void QunatityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_QunatityStateChanged
        // TODO add your handling code here:
        
        quant=Integer.parseInt(Qunatity.getValue().toString());
    }//GEN-LAST:event_QunatityStateChanged

    
    private void printButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButton4ActionPerformed
        try {
            // TODO add your handling code here:
            orderID++;
            float totel=Float.parseFloat(Grand_total.getText());
            float pay=Float.parseFloat(Pay.getText());
            float bal=pay-totel;
            Balance.setText(String.valueOf(bal));
            String billtotel=String.valueOf(totel);
            String billpay=String.valueOf(pay);
            String billbal=String.valueOf(bal);
            db=new ConnectionHelper("bill_products");
            Connection conn = db.getConnection();
            PreparedStatement statment1;
            String billPiD;
            String billPname;
            String billPprice;
            String billPquant;
            String billPTotal;
                    
            for(int i=0;i<model.getRowCount();i++){
            billPiD=(String)model.getValueAt(i,0);
            billPname=(String)model.getValueAt(i,1);
            billPprice=String.valueOf(model.getValueAt(i,2));
            billPquant=String.valueOf(model.getValueAt(i,3));
            billPTotal=String.valueOf(model.getValueAt(i,4));
            statment1=conn.prepareStatement("INSERT INTO bill_products VALUES (?,?,?,?,?,?,?)");
            statment1.setInt(1, orderID);
            statment1.setString(2, EmpId);
            statment1.setString(3, Counter);
            statment1.setString(4, billPiD);
            statment1.setString(5, billPname);
            statment1.setString(6, billPquant);
            statment1.setString(7, billPTotal);
            statment1.executeUpdate();
            }
            
            
            
            DefaultTableModel model=new DefaultTableModel();
            model=(DefaultTableModel)productTable.getModel();
            Bill bill=new Bill(billtotel,billpay,billbal,model);
            bill.setVisible(true);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_printButton4ActionPerformed

    private void editButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButton3ActionPerformed
        // TODO add your handling code here:
        int rowno=productTable.getSelectedRow();
        pid=(String)model.getValueAt(rowno,0);
        pName=(String)model.getValueAt(rowno,1);
        pPrice=Float.parseFloat(String.valueOf(model.getValueAt(rowno,2)));
        quant=Integer.parseInt(Qunatity.getValue().toString());
        float old_total=Float.parseFloat(String.valueOf(model.getValueAt(rowno,4)));
        Totel=pPrice*quant;

        model.removeRow(rowno);
        Grand_total.setText(String.valueOf(Float.parseFloat(Grand_total.getText())-old_total));
        model.addRow(new Object[]{
            pid,
            pName,
            pPrice,
            quant,
            Totel,
  
    });
        Grand_total.setText(String.valueOf(Float.parseFloat(Grand_total.getText())+Totel));
    }//GEN-LAST:event_editButton3ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
  /*  public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
/*        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POS().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Balance;
    private javax.swing.JTextField CustId1;
    private javax.swing.JTextField EmployeeId;
    private javax.swing.JTextField Ename;
    private javax.swing.JTextField Grand_total;
    private javax.swing.JTextField Pay;
    private javax.swing.JSpinner Qunatity;
    private javax.swing.JButton addButton1;
    private javax.swing.JButton clearButton5;
    private javax.swing.JButton deleteButton2;
    private javax.swing.JButton editButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton printButton4;
    private javax.swing.JTextField productId;
    private javax.swing.JTable productTable;
    // End of variables declaration//GEN-END:variables
}


