/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package invertorymanagementsystem;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ibnay
 */
public class productMenu extends javax.swing.JFrame {

    /**
     * Creates new form productMenu
     */
    
    ResultSet result,result1;
    DBO db, bc, dc;
    DefaultTableModel model;
    private final String passed_E_ID;
    private String ID;
    private String name;
    private String description;
    private String Date;
    private String Manufacture;
    private String price;
    private String feedback;
    private String department_ID;
    private String department_Category;

    ArrayList<String> comboList = new ArrayList();
   // ComboCellInsertDemo comboBoxes = new ComboCellInsertDemo();
    
    
    public void productMenu(String passed_E_ID1){
        setList();
    }
    public void setList() {
        try {

            comboList.clear();
            DBO db = new DBO("Department");
            ResultSet result = db.getResult();
            while (result.next()) {
                comboList.add(result.getString("Deplartment_Category"));

            }
        } catch (SQLException ex) {
            Logger.getLogger(productMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public productMenu(String E_ID ) throws SQLException {
        passed_E_ID = E_ID;
        db = new DBO ("products");
        
        result = db.getResult();
        initComponents();
        setList();
        setTableComboBoxes stcb = new setTableComboBoxes();
        stcb.setComboBoxes(productTable, 7, comboList);
        
        while(result.next()){
            ID = result.getString("Product_ID");
            name = result.getString("Product_Name");
            description = result.getString("Product_description");
            Date = result.getString("Product_Issue_Date");
            Manufacture = result.getString("Manufacturer");
            price = result.getString("Price");
            feedback = result.getString("Costomer_feedback");
            department_ID = result.getString("Department_ID");
            
            
            bc = new DBO ("department");
            result1 = bc.getResult();
            
            dc = new DBO ("inventory");
            
            
            while(result1.next()){
                if(department_ID.equals(result1.getString("department_ID"))){
                    department_Category = result1.getString("Deplartment_category");
                }
            }
         
            Object[] row = { ID, name, description, Date, Manufacture, price, feedback ,department_Category};

            model = (DefaultTableModel) productTable.getModel();
            model.addRow(row);
        }
    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        addButton1 = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Dubai", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(233, 166, 100));
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(233, 166, 100));
        jLabel1.setText("PRODUCT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(457, 457, 457)
                .addComponent(jLabel2))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(233, 166, 100));
        jLabel4.setText("INSPIRATION");

        deleteButton.setBackground(new java.awt.Color(51, 51, 51));
        deleteButton.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(233, 166, 100));
        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        addButton1.setBackground(new java.awt.Color(51, 51, 51));
        addButton1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        addButton1.setForeground(new java.awt.Color(233, 166, 100));
        addButton1.setText("ADD");
        addButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButton1ActionPerformed(evt);
            }
        });

        resetButton.setBackground(new java.awt.Color(51, 51, 51));
        resetButton.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        resetButton.setForeground(new java.awt.Color(233, 166, 100));
        resetButton.setText("RESET");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        saveButton.setBackground(new java.awt.Color(51, 51, 51));
        saveButton.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        saveButton.setForeground(new java.awt.Color(233, 166, 100));
        saveButton.setText("SAVE");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        productTable.setBackground(new java.awt.Color(51, 51, 51));
        productTable.setForeground(new java.awt.Color(233, 166, 100));
        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Product Description", "Product Issue Date", "Manufacturer", "Price", "Customer Feedback", "Department Category"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        productTable.setRowHeight(25);
        jScrollPane1.setViewportView(productTable);
        if (productTable.getColumnModel().getColumnCount() > 0) {
            productTable.getColumnModel().getColumn(0).setResizable(false);
            productTable.getColumnModel().getColumn(1).setResizable(false);
            productTable.getColumnModel().getColumn(2).setResizable(false);
            productTable.getColumnModel().getColumn(3).setResizable(false);
            productTable.getColumnModel().getColumn(4).setResizable(false);
            productTable.getColumnModel().getColumn(5).setResizable(false);
            productTable.getColumnModel().getColumn(6).setResizable(false);
            productTable.getColumnModel().getColumn(7).setMinWidth(100);
            productTable.getColumnModel().getColumn(7).setPreferredWidth(100);
            productTable.getColumnModel().getColumn(7).setMaxWidth(100);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resetButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saveButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(addButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deleteButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 450, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(456, 456, 456))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(deleteButton)
                        .addGap(18, 18, 18)
                        .addComponent(addButton1)
                        .addGap(18, 18, 18)
                        .addComponent(resetButton)
                        .addGap(18, 18, 18)
                        .addComponent(saveButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.dispose();
        try {
            db = new DBO("Employee");
            ResultSet data = db.getResult();
        while(data.next()){
            if( passed_E_ID.equals(data.getString("Employee_ID"))){
                new homeScreen(data).setVisible(true);
                this.dispose();
                return;
            }
        }
        new Login(false).setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(UserMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int[] rows = productTable.getSelectedRows();
            DefaultTableModel tm= (DefaultTableModel)productTable.getModel();

            while(rows.length>0)
            {
                ((DefaultTableModel)tm).removeRow(productTable.convertRowIndexToModel(rows[0]));
                rows = productTable.getSelectedRows();
            }
            productTable.clearSelection();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void addButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButton1ActionPerformed
        model = (DefaultTableModel) productTable.getModel();
            Object row[] = { null, null, null, null, null, null, null, null};
            model.addRow(row);
    }//GEN-LAST:event_addButton1ActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        try {
            DefaultTableModel model = (DefaultTableModel) productTable.getModel();
            model.setRowCount(0);
            new productMenu(passed_E_ID).setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(productMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_resetButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            db = new DBO ("products");
            Connection conn = db.getConnection();
            CallableStatement stat = conn.prepareCall("{call delete_all_Products}");
            
            stat.execute();
                
            Connection conne = db.getConnection();
            CallableStatement st = conne.prepareCall("{call insert_Products(?,?,?,?,?,?,?,?)}");
            
            for( int i=0 ; i<productTable.getRowCount() ; i++){
                String ID = productTable.getModel().getValueAt( i, 0 ).toString();
                String Name = productTable.getModel().getValueAt( i, 1 ).toString();
                String description = productTable.getModel().getValueAt( i, 2 ).toString();
                String Date = productTable.getModel().getValueAt( i, 3 ).toString();
                String Manufacturer = productTable.getModel().getValueAt( i, 4 ).toString();
                String price = productTable.getModel().getValueAt( i, 5 ).toString();
                String feedback = productTable.getModel().getValueAt( i, 6 ).toString();
                String D_ID = productTable.getModel().getValueAt( i, 7 ).toString();
                DBO bc = new DBO ("Department");
                ResultSet result = bc.getResult();
                
                st.setString(1, ID);
                st.setString(2, Name);
                st.setString(3, description);
                st.setString(4, Date);
                st.setString(5, Manufacturer);
                st.setString(6, price);
                st.setString(7, feedback);
                
                while(result.next()){
                    if(result.getString("Deplartment_Category").equals(D_ID)){
                        st.setString(8, result.getString("Department_ID"));
                    }
                }  
            st.execute();
            }
            DBO p = new DBO("products");
            ResultSet R_P = p.getResult();
            ResultSet i_p;
            DBO i;
            boolean found = false;
            //////////////insersion in inventory//////////////////
            while(R_P.next()){
                i = new DBO("inventory");
                i_p = i.getResult();
                found = false;
                while(i_p.next()){
                    if(R_P.getString("Product_ID").equals(i_p.getString("Product_ID"))){
                        found = true;
                    }
                }
                if(!found){
                    conne = i.getConnection();
                    st = conne.prepareCall("{call  insert_inventory(?,?)}");
                    st.setString(1, R_P.getString("Product_ID"));
                    st.setString(2, "0");
                    st.execute(); 
                }
                
            }
            //////////////deletion in inventory//////////////////
            p = new DBO("inventory");
            R_P = p.getResult();
          while(R_P.next()){
                i = new DBO("products");
                i_p = i.getResult();
                found = false;
                while(i_p.next()){
                    if(R_P.getString("Product_ID").equals(i_p.getString("Product_ID"))){
                        found = true;
                    }
                }
                if(!found){
                   System.out.println("executed");
                    conne = i.getConnection();
                    st = conne.prepareCall("{call  delete_inventory(?)}");
                    st.setString(1, R_P.getString("Product_ID"));
                    st.execute(); 
                }
                
            }  
            
        } catch (SQLException ex) {
            Logger.getLogger(productMenu.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
        
    }//GEN-LAST:event_saveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton1;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable productTable;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
